/// <reference types="vite/client" />

// Get contract addresses from environment variables
const getContractAddresses = () => {
  const marketplaceAddress = import.meta.env.VITE_MARKETPLACE_CONTRACT_ADDRESS;
  const tokenAddress = import.meta.env.VITE_TOKEN_CONTRACT_ADDRESS;
  
  if (!marketplaceAddress || !tokenAddress) {
    console.warn('Contract addresses not found in environment variables. Using deployed addresses.');
  }
  
  return {
    marketplace: marketplaceAddress || "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    token: tokenAddress || "0x5FbDB2315678afecb367f032d93F642f64180aa3"
  };
};

export const CONTRACT_ADDRESSES = {
  localhost: getContractAddresses(),
  holesky: getContractAddresses(),
  mainnet: getContractAddresses()
};

export const ANX_TOKEN_ADDRESS = getContractAddresses().token;
export const MARKETPLACE_ADDRESS = getContractAddresses().marketplace;

export const ABI = [
  { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "string", "name": "modelId", "type": "string" }, { "indexed": true, "internalType": "address", "name": "buyer", "type": "address" }, { "indexed": true, "internalType": "address", "name": "seller", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "price", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "txHash", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "blockNumber", "type": "uint256" } ], "name": "DatabaseModelPurchased", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "address", "name": "owner", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" } ], "name": "FundsWithdrawn", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "modelId", "type": "uint256" } ], "name": "ModelDeactivated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "modelId", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "string", "name": "modelType", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "price", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "seller", "type": "address" } ], "name": "ModelListed", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "modelId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "buyer", "type": "address" }, { "indexed": true, "internalType": "address", "name": "seller", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "price", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "platformFee", "type": "uint256" } ], "name": "ModelPurchased", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "modelId", "type": "uint256" } ], "name": "ModelReactivated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "modelId", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "string", "name": "description", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "price", "type": "uint256" } ], "name": "ModelUpdated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "address", "name": "previousOwner", "type": "address" }, { "indexed": true, "internalType": "address", "name": "newOwner", "type": "address" } ], "name": "OwnershipTransferred", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": false, "internalType": "address", "name": "account", "type": "address" } ], "name": "Paused", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "address", "name": "newToken", "type": "address" } ], "name": "PaymentTokenUpdated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": false, "internalType": "uint256", "name": "oldFee", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "newFee", "type": "uint256" } ], "name": "PlatformFeeUpdated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": false, "internalType": "address", "name": "account", "type": "address" } ], "name": "Unpaused", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "oldBalance", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "newBalance", "type": "uint256" } ], "name": "UserBalanceUpdated", "type": "event" },
  { "inputs": [], "name": "MAX_FEE_PERCENTAGE", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_modelId", "type": "string" }, { "internalType": "address payable", "name": "_sellerAddress", "type": "address" }, { "internalType": "uint256", "name": "_price", "type": "uint256" }, { "internalType": "uint256", "name": "_contractModelId", "type": "uint256" } ], "name": "buyDatabaseModel", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_modelId", "type": "string" }, { "internalType": "address payable", "name": "_sellerAddress", "type": "address" }, { "internalType": "uint256", "name": "_price", "type": "uint256" }, { "internalType": "uint256", "name": "_contractModelId", "type": "uint256" } ], "name": "buyDatabaseModelWithToken", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "buyModel", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "buyModelWithToken", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "buyerPurchases", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "", "type": "string" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "databaseModelPurchases", "outputs": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "deactivateModel", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_token", "type": "address" }, { "internalType": "uint256", "name": "_amount", "type": "uint256" } ], "name": "emergencyWithdrawToken", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "getContractBalance", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_modelId", "type": "string" } ], "name": "getDatabaseModelPurchases", "outputs": [ { "components": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "internalType": "struct AINexusMarketplace.DatabaseModelPurchase[]", "name": "", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "getModelBuyers", "outputs": [ { "internalType": "address[]", "name": "", "type": "address[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_modelId", "type": "string" } ], "name": "getModelPurchaseCount", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getModels", "outputs": [ { "components": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "modelType", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "bool", "name": "sold", "type": "bool" }, { "internalType": "bool", "name": "active", "type": "bool" }, { "internalType": "uint256", "name": "createdAt", "type": "uint256" }, { "internalType": "uint256", "name": "totalSales", "type": "uint256" } ], "internalType": "struct AINexusMarketplace.Model[]", "name": "", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_seller", "type": "address" } ], "name": "getModelsBySeller", "outputs": [ { "internalType": "uint256[]", "name": "", "type": "uint256[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_buyer", "type": "address" } ], "name": "getPurchasesByBuyer", "outputs": [ { "internalType": "uint256[]", "name": "", "type": "uint256[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getTotalModels", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" } ], "name": "getUserContractModelPurchaseCount", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" } ], "name": "getUserDatabaseModelPurchaseCount", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_userAddress", "type": "address" } ], "name": "getUserPurchases", "outputs": [ { "components": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "internalType": "struct AINexusMarketplace.DatabaseModelPurchase[]", "name": "", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_userAddress", "type": "address" } ], "name": "getUserSales", "outputs": [ { "components": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "internalType": "struct AINexusMarketplace.DatabaseModelPurchase[]", "name": "", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" } ], "name": "getUserTotalPurchaseCount", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "string", "name": "", "type": "string" } ], "name": "hasPurchasedDatabaseModel", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "hasPurchasedModel", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" }, { "internalType": "string", "name": "_modelId", "type": "string" } ], "name": "hasUserPurchasedDatabaseModel", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" }, { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "hasUserPurchasedModel", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_modelType", "type": "string" }, { "internalType": "string", "name": "_description", "type": "string" }, { "internalType": "uint256", "name": "_price", "type": "uint256" } ], "name": "listModel", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "", "type": "uint256" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "modelBuyers", "outputs": [ { "internalType": "address", "name": "", "type": "address" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "", "type": "string" } ], "name": "modelPurchaseCount", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "models", "outputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "modelType", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "bool", "name": "sold", "type": "bool" }, { "internalType": "bool", "name": "active", "type": "bool" }, { "internalType": "uint256", "name": "createdAt", "type": "uint256" }, { "internalType": "uint256", "name": "totalSales", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "owner", "outputs": [ { "internalType": "address", "name": "", "type": "address" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" }, { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "ownsModel", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "pause", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "paused", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "paymentToken", "outputs": [ { "internalType": "contract IERC20", "name": "", "type": "address" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "platformFeePercentage", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" } ], "name": "reactivateModel", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "renounceOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "sellerModels", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_token", "type": "address" } ], "name": "setPaymentToken", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "newOwner", "type": "address" } ], "name": "transferOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "unpause", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_modelId", "type": "uint256" }, { "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_description", "type": "string" }, { "internalType": "uint256", "name": "_price", "type": "uint256" } ], "name": "updateModel", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_newFeePercentage", "type": "uint256" } ], "name": "updatePlatformFee", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "string", "name": "_modelId", "type": "string" }, { "internalType": "uint256", "name": "_purchaseIndex", "type": "uint256" }, { "internalType": "string", "name": "_txHash", "type": "string" } ], "name": "updatePurchaseTxHash", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" } ], "name": "userBalances", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "userPurchases", "outputs": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "userSales", "outputs": [ { "internalType": "string", "name": "modelId", "type": "string" }, { "internalType": "uint256", "name": "contractModelId", "type": "uint256" }, { "internalType": "address", "name": "buyer", "type": "address" }, { "internalType": "address payable", "name": "seller", "type": "address" }, { "internalType": "uint256", "name": "price", "type": "uint256" }, { "internalType": "uint256", "name": "platformFee", "type": "uint256" }, { "internalType": "uint256", "name": "sellerAmount", "type": "uint256" }, { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }, { "internalType": "uint256", "name": "timestamp", "type": "uint256" }, { "internalType": "string", "name": "txHash", "type": "string" }, { "internalType": "bool", "name": "isDatabaseModel", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "withdrawFunds", "outputs": [], "stateMutability": "nonpayable", "type": "function" }
];
